export const traumaCategory = {
  id: "trauma",
  title: "Trauma",
  subtitle: "Understanding trauma and finding a path toward healing",
  resources: [
    {
      type: "info",
      name: "Effects of Trauma - Adults",
      description: "Common immediate and long-term responses to traumatic events",
      sections: [
        {
          heading: "Immediate Effects",
          bullets: [
            "Shock, numbness",
            "Confusion, disorientation",
            "Fear or anger",
            "Anxiety, worry, irritability",
            "Grief, sadness, feelings of loss",
            "Heightened perceptions",
            "Intrusive thoughts and images",
            "Fatigue, muscle tension",
            "Self-blame, guilt",
            "Shame, embarrassment",
            "Courage, determination",
            "Optimism or gratitude",
            "Alertness, increased energy",
            "Increased faith or loss of faith",
            "Social withdrawal or greater need for connectedness",
          ],
        },
        {
          heading: "Long-Term Effects",
          bullets: [
            "Being easily startled by noises or unexpected touch",
            "Nightmares and flashbacks",
            "Feelings of detachment",
            "Hyper-alertness, hyper-vigilance, jumpiness",
            "Emotional numbing or restricted range of feelings",
            "Diminished interest in everyday activities",
            "Feeling helpless, panicked, or out of control",
            "Irritability and restlessness",
            "Difficulty concentrating or remembering things",
            "Difficulty trusting, feelings of betrayal",
            "Outbursts of anger or rage, emotional mood swings",
            "Aches and pains: headaches, backaches, stomachaches",
            "Constipation or diarrhea",
            "Sudden sweating and/or heart palpitations (fluttering)",
            "Changes in sleep patterns",
            "Developing or losing interest in sex",
            "Panic attacks, anxiety, or depression",
            "Conflict with others",
            "Lack of motivation",
          ],
        },
      ],
    },
    {
      type: "info",
      name: "Effects of Trauma - Children",
      description: "How domestic violence and trauma affect children at every age",
      sections: [
        {
          intro: "Children are exposed to and experience domestic violence in many ways. They may hear one parent/caregiver threaten the other, observe a parent out of control or reckless with anger, see one parent assault the other, or live with the aftermath of a violent assault.",
        },
        {
          alert: "Children are negatively affected by hearing threats to the safety of their caregiver, regardless of whether it results in physical injury. Children who live with domestic violence are at increased risk to become victims of child abuse.",
        },
        {
          intro: "Be honest with your children about what is happening. Studies show most children are aware of the violence in the home. Respecting their knowledge will increase their trust in you.",
        },
        {
          heading: "Short-Term Effects",
          bullets: [
            "Generalized anxiety",
            "Sleeplessness",
            "Nightmares",
            "Difficulty concentrating",
            "High activity levels",
            "Increased aggression",
            "Increased anxiety about being separated from a parent",
            "Intense worry about their safety or the safety of a parent",
          ],
        },
        {
          heading: "Long-Term Effects",
          bullets: [
            "Physical health problems",
            "Behavior problems in adolescence (juvenile delinquency, alcohol, substance abuse)",
            "Emotional difficulties in adulthood (depression, anxiety disorders, PTSD)",
            "Impaired social skills",
          ],
        },
        {
          intro: "Children exposed to domestic violence often learn destructive lessons about violence and power in relationships. Children may learn that it is acceptable to exert control or relieve stress by using violence, or that violence is in some way linked to expressions of intimacy and affection. These lessons can have a powerful negative effect on children in social situations and relationships throughout childhood and in later life.",
        },
        {
          heading: "Child Traumatic Stress (CTS)",
          intro: "CTS is a psychological reaction children have to a traumatic experience, such as:",
          bullets: [
            "Car accidents",
            "Serious injuries",
            "Seeing or hearing acts of violence",
            "Terrorism",
            "Physical or sexual abuse",
            "Medical procedures",
            "The unexpected death of a loved one",
            "Life-threatening natural disasters",
          ],
        },
        {
          noDivider: true,
          intro: "Children suffering from CTS have lingering reactions to trauma. This affects their daily lives long after the trauma has ended.",
          bullets: [
            "Intense and ongoing emotional upset",
            "Depression",
            "Anxiety",
            "Behavioral changes",
            "Difficulties at school",
            "Problems maintaining relationships",
            "Difficulty eating and sleeping",
            "Aches and pains",
            "Withdrawal",
            "Substance abuse, dangerous behaviors, or unhealthy sexual activity among older children",
          ],
        },
        {
          heading: "Young Children",
          bullets: [
            "Feel completely helpless and passive and quiet",
            "Cry for help or desperately wish for someone to intervene",
            "Feel deeply threatened by separation from parents or caretakers",
            "Become upset when they hear cries of distress from a parent or caretaker",
            "Rely on a protective shield provided by adults and older siblings who can judge the seriousness of danger and ensure their safety and welfare",
            "Be the target of physical and sexual abuse by the very people they rely on for their protection and safety",
            "Witness violence within the family or be left helpless after a parent or caretaker is injured, as might occur in a serious automobile accident",
            "Become easily alarmed",
            "Their minds may stay on a central action, like being hit or seeing someone fall to the floor",
            "May have simple thoughts about protection, for example, \"Daddy hit mommy, mommy call police\"",
            "Can become more generally fearful, especially in regard to separations and new situations",
            "In circumstances of abuse by a parent or caretaker, the young child may act confused as to where to find protection and where there is threat",
            "May respond to very general reminders of a trauma, like the color red or the sounds of another child crying",
          ],
        },
        {
          heading: "School-Age Children",
          bullets: [
            "May judge the seriousness of a threat and think about protective actions",
            "Usually do not see themselves as able to counter serious danger directly, but imagine actions they wish they could take, like those of their comic book heroes",
            "May feel like failures for not doing something helpful in traumatic situations involving violence against family members",
            "May feel ashamed or guilty",
            "Trauma can happen at home or other places, such as school, etc.",
            "Respond to concrete reminders about the trauma, such as someone with the same hairstyle as an abuser or the playground monkey bars where a child was hurt",
            "Likely to develop intense, specific new fears linking back to the original danger",
            "Can easily have fears of recurrence that result in avoiding things they like to do",
            "May go back and forth between shy or withdrawn behavior and unusually aggressive behavior",
            "Can have thoughts of revenge they cannot resolve",
            "Normal sleep patterns can be easily disturbed. They can move around restlessly in their sleep, vocalize, and wake up tired",
            "Lack of restful sleep can interfere with their daytime concentration and attention",
            "Difficult for them to study because they remain on alert for things happening around them",
          ],
        },
        {
          heading: "Adolescents",
          intro: "With the help of friends, adolescents begin actively judging and addressing dangers on their own. This is a developing skill and many things can go wrong along the way. With independence, adolescents can be in more situations turning from danger to trauma. They could:",
          bullets: [
            "Be drivers or passengers in car accidents",
            "Be victims of rape, dating violence, and criminal assault",
            "Be present during school or community violence",
            "Lose friends under traumatic circumstances",
            "Be a victim of bullying, in person or online",
          ],
        },
        {
          noDivider: true,
          intro: "During traumatic situations, adolescents make decisions about whether and how to intervene, and about using violence to counter violence. They can feel guilty, thinking their actions made matters worse.",
        },
        {
          noDivider: true,
          intro: "Adolescents are learning to handle intense physical and emotional reactions to take action in the face of danger. They are also learning more about human motivation and intent, and struggle over issues of irresponsibility, teenage angst, and human accountability.",
        },
        {
          noDivider: true,
          intro: "Adolescents are particularly challenged by reactions that persist after traumatic experiences. They may:",
          bullets: [
            "Easily interpret many reactions as being regressive or childlike",
            "Interpret their reactions as signs of \"going crazy,\" or being weak or different from everyone else",
            "Experience exaggerated physiological responses",
            "Believe they are unique in their pain and suffering",
            "Be sensitive to the failure of family, school, or community to protect them or carry out justice",
            "Turn even more to peers to judge risks and to take protective action",
            "Be especially \"grossed out\" or fascinated by grotesque injury or death, and remain focused on their own scars that serve as daily trauma reminders",
            "Respond to their experience through dangerous reenactment behavior – that is, by reacting with too much \"protective\" aggression for a situation at hand",
            "Go to two extremes: reckless behavior endangering themselves and others, or extreme avoidant behavior that can derail their adolescent years",
            "Try to rid post-trauma emotions and physical responses through alcohol and drugs",
            "Their sleep disturbance can remain hidden by late night studying, television watching, and partying",
            "It is a dangerous mix when adolescent thoughts of revenge are added to their usual feelings of invulnerability",
            "The avoidant life of an adolescent may go unnoticed",
          ],
        },
      ],
      disclaimer: "Adapted from The National Child Traumatic Stress Network: www.nctsn.org",
    },
    {
      type: "info",
      name: "Adverse Childhood Experiences (ACEs)",
      description: "Understanding the long-term health impact of childhood trauma",
      sections: [
        {
          intro: "Adverse childhood experiences (ACEs) are stressful or traumatic events that are a significant risk factor for a wide range of health problems throughout a person's lifespan, including substance abuse.",
        },
        {
          heading: "ACEs Include",
          bullets: [
            "Physical abuse and neglect",
            "Sexual abuse",
            "Emotional abuse and neglect",
            "Intimate partner violence",
            "Seeing mother or parent treated violently",
            "Substance abuse in household",
            "Household mental illness",
            "Parental separation or divorce",
            "Incarcerated family member",
          ],
        },
      ],
      disclaimer: "To learn more about ACEs or take the ACE quiz, visit acestoohigh.com/got-your-ace-score.",
    },
  ],
};
