export const unhealthySignsCategory = {
  id: "unhealthy-signs",
  title: "Unhealthy Relationship Signs",
  subtitle: "Recognizing abusive behaviors, warning signs, and their effects",
  resources: [
    {
      type: "info",
      name: "Unhealthy Relationship Signs",
      description: "Common patterns and behaviors that signal an abusive relationship",
      sections: [
        {
          alert: [
            "It's not always easy to tell at the beginning of a relationship if your partner will become abusive.",
            "Abusive behaviors grow and intensify over time.",
          ],
        },
        {
          heading: "Quick Involvement",
          intro: "Abusers often start relationships very quickly. Many victims dated or knew their abuser less than six weeks before they were engaged or living together.",
        },
        {
          heading: "Jealousy",
          intro: "Jealousy is not a sign of love; it is a sign of insecurity and possessiveness. An abuser may monitor their partner's time closely, check mileage on their car, drop by unexpectedly, or even refuse to allow the victim to work. The victim is accused of nonexistent affairs and flirting.",
        },
        {
          heading: "Control and Isolation",
          intro: "Abusers gradually take control of their partner's actions. The abuser often controls the money, what their partner does, who their partner sees, and may refuse to let their partner leave home. Abusers cut their partner off from friends, family, and supportive people, making them dependent on the abuser.",
        },
        {
          heading: "Unrealistic Expectations",
          intro: "Abusers expect their partner to be perfect and use \"mistakes\" as an excuse to exert control and violence.",
        },
        {
          heading: "Emotional Abuse",
          intro: "Abusers degrade their partner by telling them they are stupid, ugly, and incompetent. Insecure people are easier to control.",
        },
        {
          heading: "Blames Others for Problems and Feelings",
          intro: "Abusers blame their partner for almost everything that goes wrong. Abusers are easily insulted and take normal parts of life as personal attacks (being asked to help, getting a ticket, a change in the economy, etc).",
        },
        {
          heading: "Sudden Mood Changes",
          intro: "Moods change quickly for no apparent reason. Abusers often blame the victim.",
        },
        {
          heading: "Collateral Damage",
          intro: "Throwing objects, putting holes in walls, breaking victim's property to establish dominance.",
        },
        {
          heading: "Threats of Violence",
          intro: "Abusers use threats of force to control their partner. They may threaten violence against children, pets, extended family, etc.",
        },
        {
          heading: "Past Violence",
          intro: "Abusers may tell their partner they have abused past partners to intimidate and control. This indicates an abusive pattern of behavior.",
        },
        {
          heading: "Cruelty to Animals or Children",
          intro: "Abusers may attack animals and children to terrorize their partner. Abusers tend to be insensitive to the needs, feelings, suffering, and pain of children and animals. Abusers expect children and animals to do things beyond their abilities and may punish them if they do not.",
        },
        {
          heading: "Rigid Sex Roles",
          intro: "Abusers may rely on traditional sex roles, making their partner responsible for meeting all needs. Abusers may express superiority to their partner, force sex, and demand servitude.",
        },
        {
          heading: "\"Playful\" Use of Force in Sex",
          intro: "Abusers show little concern about their partner and whether or not their partner wants to have sex. Abusers may use violence during sexual acts to make violence seem normal and playful.",
        },
        {
          heading: "Use of Force During an Argument",
          intro: "Includes holding someone down, restraining from leaving, pulling hair, dragging, throwing, pushing/shoving, slapping, punching, strangling, stabbing, etc.",
        },
        {
          heading: "Possible Warning Signs",
          bullets: [
            "Keeping you or discouraging you from seeing friends or family members",
            "Insulting, demeaning or shaming you with put-downs",
            "Controlling every penny spent in the household",
            "Taking your money or refusing to give you money for expenses",
            "Looking at you or acting in ways that scare you",
            "Controlling who you see, where you go, or what you do",
            "Preventing you from making your own decisions",
            "Telling you that you are a bad parent or threatening to harm or take away your children",
            "Preventing you from working or attending school",
            "Destroying your property",
            "Threatening to hurt or kill your pets",
            "Intimidating you with guns, knives or other weapons",
            "Pressuring you to have sex or do things sexually you're not comfortable with",
            "Pressuring you to use drugs or alcohol",
          ],
        },
      ],
      disclaimer: "For more information, visit The National Domestic Violence Hotline at www.thehotline.org/is-this-abuse/abuse-defined/.",
    },
    {
      type: "info",
      name: "Types of Abuse",
      description: "Recognizing the many forms abuse can take in a relationship",
      sections: [
        {
          heading: "Emotional Abuse",
          bullets: [
            "Always accompanies, and in most cases precedes, physical abuse",
            "Can severely affect the victim's sense of self and reality",
            "Hurtful behaviors, words, and actions designed to degrade, intimidate, manipulate, isolate, or humiliate",
            "Name calling",
            "Yelling",
            "Frightening or intimidating",
            "Threats of suicide or homicide",
            "Constantly attacking self-esteem",
            "Destroying property or sentimental items",
            "Threatening to take or hurt children or pets",
            "Isolation from friends and/or family",
            "Threatening to tell friends or family lies",
            "Insulting characteristics of victim – age, race, values, culture, abilities, etc.",
            "Cleaning guns or knives in front of the victim",
            "Blaming victim for all the abuser's troubles and failures",
            "Not permitting victim to do certain things",
            "Questioning the victim's logic, sanity, or ability to make decisions",
            "Repeated statements to convince the victim that no one else will love him/her",
            "In same gender relationships, threatening to \"out\" someone",
            "With undocumented individuals, threatening to call ICE or threats of deportation",
            "With people with different abilities, withholding or destroying assistance devices",
          ],
        },
        {
          heading: "Social Abuse",
          bullets: [
            "Isolates partner from others, including extended family; the fewer social connections the partner has, the more control the abuser has",
            "Insisting the couple spend all time together",
            "Discouraging or forbidding the victim from seeing friends or family",
            "Monitoring the victim's mail, phone calls, or social media",
            "Checking the odometer",
            "Restricting access to the car or car keys",
            "Telling others the victim is crazy or abusive",
          ],
        },
        {
          heading: "Physical Abuse",
          bullets: [
            "Often begins with less violent actions and escalates",
            "Less visible areas of the body may be targeted, such as abdomen, buttocks, breasts, scalp, etc.",
            "Pinching and/or squeezing in a painful way",
            "Trapping, blocking, restraining",
            "Biting, spitting, pinching, pulling/grabbing hair",
            "Slapping, kicking, tripping, pushing, or punching",
            "Throwing objects",
            "Hitting the victim's head against door, wall, or floor",
            "Strangling, smothering",
            "Denying the victim medical treatment",
            "Not allowing food or access to bathroom, medicine, disrupting sleep",
            "Use of weapons",
            "Homicide",
            "Marriage or pregnancy can increase abuse",
          ],
        },
        {
          heading: "Spiritual Abuse",
          bullets: [
            "Using teachings and traditions to encourage, excuse, and justify power",
            "Convince the victim they are to blame for the crimes or sins of the abuser",
            "Forcing conversion to a different religion",
            "Not allowing a victim to practice their religion or attend religious services",
            "Forcing attendance at religious services",
            "Degrading what is sacred to a victim",
            "Humiliation in front of people affiliated with the victim's religion or spirituality",
          ],
        },
        {
          heading: "Sexual Abuse",
          bullets: [
            "Degrading comments about the victim's body or sexual performance",
            "Objectification of the victim's body",
            "Sexual jokes",
            "Criticizing the victim's sexuality or sexual preferences",
            "Withholding sex",
            "Forcing, coercing, or intimidating the victim into having sexual contact or intercourse",
            "Forcing sexual contact with other individuals",
            "Refusal to share information about past sexual history or STDs",
            "Knowingly not using protection to infect someone with STDs, including HIV and hepatitis",
            "Forcing a person to look at, engage in, or pose for pornography",
            "Coercing prostitution",
            "Forcing sex after physical assault",
            "Forcing children to witness sexual contact",
            "Rape, sodomy",
            "Forcing the use of or prohibiting the use of contraception",
            "Forcing or forbidding an abortion",
            "Using weapons in sexual acts",
            "Affairs and infidelity",
          ],
        },
        {
          heading: "Technology Abuse",
          bullets: [
            "Controls social media contacts",
            "Uses social media sites to monitor your locations",
            "Looks through phone or tablet frequently",
            "Monitors texts, emails, and looks at your pictures",
            "Sends negative, insulting, or threatening messages or emails",
            "Insults you in posts or status updates",
            "Insists on having your passwords",
            "Pressures you to send explicit photos or videos",
            "Sends you unwanted explicit photos or videos",
          ],
        },
        {
          heading: "Financial Abuse",
          bullets: [
            "Keeping financial secrets",
            "Not permitting work, forcing multiple jobs",
            "Controlling all household income; forcing victim to turn over paychecks to abuser",
            "Harassing or stalking at a workplace",
            "Withholding or taking debit or credit cards",
            "Taking money from savings or retirement",
            "Engaging in behaviors that may lead to eviction",
            "Monitoring the victim's spending",
            "Forcing the household to live beyond their means",
            "Having only the abuser's or only the victim's name on all property and accounts",
            "Controlling all financial decisions for the household",
          ],
        },
      ],
    },
    {
      type: "info",
      name: "Strangulation",
      description: "What you need to know about one of the most lethal forms of violence",
      sections: [
        {
          paragraphs: [
            "Strangulation is one of the most lethal forms of violence. It is often incorrectly referred to as \"choking.\"",
            "Strangulation can cause unconsciousness within seconds and death within minutes, days, or weeks. Abusers use hands, arms, legs, cords, belts, or other objects to strangle the victim. This stops blood flow to the brain and keeps the victim from being able to breathe.",
          ],
        },
        {
          heading: "Key Facts",
          bullets: [
            "When an abuser strangles you, they are showing intent and ability to kill.",
            "Strangulation is extremely dangerous and considered the best predictor of future homicide.",
            "Almost 70% of victims will experience near-fatal strangulation repeatedly.",
            "Strangulation causes 10% of violent deaths per year in the U.S.",
          ],
        },
        {
          alert: "If your partner has strangled you, you are 10 times more likely to be killed by them.",
        },
        {
          paragraphs: [
            "Effects of strangulation—including brain damage, difficulty breathing, dizziness, miscarriage, and death—can set in hours or days after the incident. Many victims show zero visible signs after strangulation.",
            "We strongly encourage anyone who has been a victim of strangulation to seek medical treatment immediately. Crime Victim's Compensation may be available to help assist you. Even if you feel okay, your life could depend on it.",
          ],
        },
        {
          heading: "Potential Symptoms",
          bullets: [
            "Sore throat",
            "Difficulty swallowing",
            "Neck pain",
            "Hoarseness",
            "Bruising on the neck or behind your ears",
            "Discoloration on your tongue",
            "Ringing in your ears",
            "Bloodshot eyes",
            "Dizziness",
            "Memory loss",
            "Drooling",
            "Nausea or vomiting",
            "Difficulty breathing",
            "Incontinence",
            "A seizure",
            "A miscarriage",
            "Changes in mood or personality: agitation, aggression, etc.",
            "Changes in sleep patterns",
            "Changes in vision such as blurriness or seeing double",
            "Fainted or lost consciousness",
          ],
        },
        {
          heading: "Monitor and Log Your Signs",
          intro: "Keep a record of any injuries you experience from being strangled, including changes of the injuries over time after the assault. For each incident, note:",
          bullets: [
            "Date and time",
            "Visible signs",
            "Whether you took a photo",
            "What else you felt or experienced",
          ],
        },
      ],
      disclaimer: "Tennessee Victims of Crime Compensation Fund: treasury.tn.gov/Services/Claims-and-Risk-Management/Criminal-Injuries-Compensation",
    },
    {
      type: "info",
      name: "Domestic Violence and Pregnancy",
      description: "The risks and effects of abuse during and after pregnancy",
      sections: [
        {
          heading: "The Facts",
          bullets: [
            "Pregnant and postpartum women are more likely to die by homicide than any other cause of death.",
            "Most female homicide victims are killed by their intimate partner.",
            "DV during pregnancy risks both the mom's and baby's lives.",
            "Abusive partners do not stop violent behavior after the baby is born.",
            "If you are a victim of domestic violence and are pregnant, you and your baby are at high risk of injury or murder.",
            "Abuse affects the emotional and physical welfare of you and your baby.",
            "Domestic violence is the number one predictor of child abuse.",
          ],
        },
        {
          alert: "Domestic violence is the leading cause of injury to women (pregnant or not), more than car accidents, muggings, and rape combined.",
        },
        {
          heading: "Physical Effects of Violence During Pregnancy",
          bullets: [
            "Suicide",
            "Murder",
            "Miscarriage",
            "Hemorrhage",
            "Vaginal bleeding",
            "Uterine infection",
            "Physical injuries",
            "Low birth weight",
            "Abdominal trauma",
            "Delayed prenatal care",
            "Ruptured membranes",
            "Insufficient weight gain",
            "Alcohol and drug abuse",
            "Increase of chronic illness",
            "Complications during labor",
            "Stress, depression, anxiety",
            "Separation of the placenta",
            "Vaginal/cervical/kidney infections",
            "Fetal bruising, fractures, and blood clots",
          ],
        },
      ],
      disclaimer: "For more information, visit the Center for Hope and Safety at hopeandsafety.org.",
    },
  ],
};
