import { Montserrat, Nunito } from "next/font/google";
import "./globals.css";

// font weights: 400 = Regular, 700 = Bold, 800 = Extra Bold
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "800"], // 400 = Regular, 800 = Extra Bold
});

// font weights: 700 = Bold
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["700"], // 700 = Bold
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${nunito.variable} h-full antialiased light`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
